### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by araid** [Patitotective/ImThemes#20]
I love the idea of this app and would like to use it on macOS. How hard would it be to add support for it?

I'm happy to try compiling but I've never worked with nim. I'd appreciate any links to guides or resources.

**Comment by Patitotective** [comment]
Hi.
I've never used MacOS so I'm unsure how you create a MacOS app but I think that since MacOS is based in Linux, you could compile the app in your computer and it should work.

To compile ImThemes on your computer follow these steps:
1. Open your terminal and copy `curl https://nim-lang.org/choosenim/init.sh -sSf | sh`, it will download choosenim, which is a Nim installer/version manager. More info at https://nim-lang.org/install_unix.html
2. Don't forget to add `~/.nimble/bin` to your `PATH` variable (so you can use commands like `nimble` or `nim`) in your terminal.
3.  Clone this repository. With `git clone https://github.com/Patitotective/ImThemes`.
4. Then go to the directory of the clone and type `nimble install -y`, this will install all the Nim dependencies.
5. Compile the application with `nimble buildBin`, and try running that file.

**Comment by Patitotective** [comment]
This seems useful if we want to have a prebuilt MacOS app https://forum.nim-lang.org/t/2652

**Comment by bradparks** [comment]
fyi, I tried this, but I get this error with either brew installed nim, or nim installed via process above ^^^

also, where are the themes stored? Can I find them on a website somewhere and browse them? Thanks!

<img width="1435" alt="image" src="https://github.com/Patitotective/ImThemes/assets/185477/9ecba9c0-9275-4dc8-a08a-24a4c7a296d0">

**Comment by Patitotective** [comment]
@bradparks
1. Try running it with the `--deepcopy:on` flag, this is the explanation I found:

> If you use system.deepCopy in your code, you need to enable it via --deepCopy:on on the command line. This is a band-aid and a better solution for this will arrive in the future. The reason for this opt-in switch is that ARC and ORC do not use the old runtime type information (RTTI) that system.deepCopy is built upon. We’ve built ARC and ORC with embedded devices in mind where the overhead of the old RTTI has been reported to be unacceptable.

https://forum.nim-lang.org/t/9868#65096

2. The themes are stored in the GitHub repository itself at https://github.com/Patitotective/ImThemes/blob/main/themes.toml, to browse them you can use ImThemes itself. If you mean where are the themes stored in your computer, they are stored using the [getCacheDir](https://nim-lang.org/docs/osappdirs.html#getCacheDir) procedure which says:
> On Windows: getEnv("LOCALAPPDATA")
> On macOS: getEnv("XDG_CACHE_HOME", getEnv("HOME") / "Library/Caches")
> On other platforms: getEnv("XDG_CACHE_HOME", getEnv("HOME") / ".cache")

**Comment by bradparks** [comment]
cool - tnanks - I tried it and get another error now - I will review the themes in that folder too though - much appreciated, and no pressure, lol!

<img width="2048" alt="image" src="https://github.com/Patitotective/ImThemes/assets/185477/5863dd3e-bacb-4e5b-b13c-975c09675b85">

**Comment by Patitotective** [comment]
Hmm, that's a weird error. Seems like imgui isn't being imported correctly or something of the sort, did you do `nimble install nimgl`? You can check looking for `nimgl` in the output of `nimble list -i` (or directly do `nimble list -i | grep nimgl`).

**Comment by bradparks** [comment]
it is installed

<img width="792" alt="image" src="https://github.com/Patitotective/ImThemes/assets/185477/e18294fa-500e-4d07-a4fe-8f2ec2f915ed">

but I tried to install afterwards to see, and it said it was already there (same version)

<img width="1221" alt="image" src="https://github.com/Patitotective/ImThemes/assets/185477/302a9828-b1e1-44b0-822b-9ab9c7d3de7a">

no biggie - I can use the themes as is! much appreciated!

**Comment by kasperhbo** [comment]
It this maybe akready solved?

**Comment by Patitotective** [comment]
I guess I'll close it since it seems you can compile ImThemes without problems on MacOS.
