### ISSUE TITLE
ImThemes won't open sometimes

### ISSUE THREAD

**Issue by yhqe** [Patitotective/ImThemes#22]
Sometimes when I go to use ImThemes, it just won't open. I've tried running it normally, as admin, and even running it in cmd to see if it outputted any errors, but nothing. I've tried building it from source, but nimble keeps complaining about "invalid indentation".

Heres an example with Process Hacker open:

![chrome_n5c7vEU7hh](https://github.com/Patitotective/ImThemes/assets/139268606/166e8abf-21af-426c-bd92-8f99ccf6ead7)

(running as admin stopped the recording, but it didn't open even running as admin)

Any fixes/solutions?

**Comment by paysonism** [comment]
I have this issue too idk what to do abt it

**Comment by Fiendssov** [comment]
C:\Users\User\AppData\Local
and delete "ImThemes"

**Comment by Patitotective** [comment]
@yhqe and @paysonism, the issue is probably related to the configuration/cache files that are stored in the directory mentioned by Fiendssov C:\Users\User\AppData\Local\ImThemes. To prevent this issue in future versions it would be really helpful if you could send the files of that folder to me.
Thank you and sorry for answering this late.
